### ISSUE TITLE
Tagging

### ISSUE THREAD

**Issue by cofl** [AggressiveAluminum/Monoglot#22]
As a user, I want to organize my words by arbitrary groups and mark them with arbitrary tags not necessarily related to their grammatical function, to better organize my lexicon.

As a viewer, I want to see what words go in which groups, so I can see, for example, which words use some classifier, or what words aren't complete so I know to be careful when using them.

Developer note:
Basically, have a class like Headword, where there are fields matching the ones in SQL, and update/select/insert/delete functions.

**Comment by cofl** [comment]
Only user-created tags are supported, we don't make any.

**Comment by softwarexplorer** [comment]
new methods for Tagging:

static Tag createTag(name)
Tag updateName(newName)
Tag updateDescriptions(newDescription)
List<Tag> fetch(All)
List<Tag> fetchFor(HeadWord)
static void delete(Tag)
