### ISSUE TITLE
Product Documentation

### ISSUE THREAD

**Issue by amstanag** [AggressiveAluminum/Monoglot#3]
Included documentation for all included features; nothing fancy, just enough to be useful.

**Comment by cofl** [comment]
This is gonna require the other parts to be more-or-less done and functional, I think

**Comment by amstanag** [comment]
Yeah I just realized that earlier.. I can help with other things if people need it as well so I'm not useless until then..

-Alex

**Comment by cofl** [comment]
Any ideas for implementation on #2 (DB)?

**Comment by amstanag** [comment]
I'll look at it more later, but using java to work with a database is kind of annoying.. do able though

**Comment by cofl** [comment]
Given the state of the project, I think it's best we move this back to 0.2.

**Comment by amstanag** [comment]
Alright, sounds good to me

**Comment by amstanag** [comment]
This is moving down in priority to the end of the project (as of now). Just putting this here as a reminder.

**Comment by cofl** [comment]
Basics are there, now just a bunch of HTML.

**Comment by cofl** [comment]
Could I plan with someone to sit down and hammer this out?
